# Generated by Django 3.2 on 2022-12-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('birthday_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('dni_number', models.IntegerField(blank=True, null=True, verbose_name='Número de Documento')),
                ('location', models.CharField(max_length=40, verbose_name='Localidad')),
                ('phone_number', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('health_insurance_name', models.CharField(max_length=10, verbose_name='Obra social')),
                ('health_insurance_number', models.IntegerField(blank=True, max_length=15, null=True, verbose_name='Número de Afiliado')),
                ('school_level', models.CharField(max_length=15, verbose_name='Nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('dx_code', models.CharField(max_length=60, verbose_name='Código')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, max_length=40, null=True, verbose_name='Localidad')),
                ('address', models.CharField(blank=True, max_length=60, null=True, verbose_name='Dirección')),
                ('phone_number', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('location', models.CharField(max_length=40, verbose_name='Localidad')),
                ('phone_number', models.IntegerField(max_length=10, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile', models.CharField(max_length=20, verbose_name='Profesión')),
                ('has_experience', models.BooleanField(verbose_name='Experiencia')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre Escuela')),
                ('school_type', models.CharField(max_length=15, verbose_name='Tipo Escuela')),
                ('location', models.CharField(max_length=40, verbose_name='Localidad')),
                ('address', models.CharField(max_length=60, verbose_name='Dirección')),
                ('phone', models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.person')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('contract_type', models.CharField(max_length=15, verbose_name='Tipo')),
                ('is_active', models.BooleanField(verbose_name='Activo')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
                ('obs', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.client')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.school')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.therapist')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='dx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='entity.diagnostic'),
        ),
    ]
