# Generated by Django 3.2 on 2022-12-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dx',
            new_name='diagnostic',
        ),
    ]
